### PR TITLE
Make Brains and Beards website mobile responsive

### PR DESCRIPTION
**Pull request by lawmbass**
Using [Bootstrap 4](http://getbootstrap.com/)

screen shot 2017-10-13 at 10 50 39 pm
screen shot 2017-10-13 at 10 51 00 pm
screen shot 2017-10-13 at 10 51 11 pm
screen shot 2017-10-13 at 10 51 28 pm
screen shot 2017-10-13 at 10 51 42 pm

### CODE REVIEW

**Comment by lawmbass** [comment]
Fixes #1

**Comment by lawmbass** [comment]
Hey @sharnik, can you give me some feedback on this PR

**Comment by sharnik** [comment]
Sorry for late response, I just had a chance to look at it. 
First of all, thank you so much for your work, we really appreciate it! It looks great on small screens now.

A little bit of nitpicking:
* I saw that you changed the indentation from 2 spaces to a tab, we'll need to re-format that
* We need to add a max-width, because it looks bad on really wide screens:
screen shot 2017-10-19 at 08 33 28

If you have a minute, you can update the PR, or I'll add those small changes myself when merging over the weekend.

**Comment by lawmbass** [comment]
Good catch, sure I'll make those changes to the PR this evening 👌

**Comment by lawmbass** [comment]
- [x] Change indentation from tabs to 2 spaces
- [x] Add max-width to prevent content overflow on large screens

**Comment by lawmbass** [comment]
Hey @sharnik, I've gone ahead and made the necessary changes to fix the issues you came across earlier. Let me know what you think. 👍

**Comment by sharnik** [comment]
Thanks so much, merged!

**Comment by lawmbass** [comment]
No problem, I had fun working on it 😄

**Pull request merged**
